/* ============================================================
   TWØLVE — motivation quotes
   Edit freely: each item is { text, by }.
   Add, remove or reorder — the app picks one at random on login.
   ============================================================ */
const USER_NAME = "TAI";   // ← your name, used in the login greeting
const QUOTES = [
  { text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", by: "Marcus Aurelius" },
  { text: "Waste no more time arguing about what a good person should be. Be one.", by: "Marcus Aurelius" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", by: "Marcus Aurelius" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", by: "Marcus Aurelius" },
  { text: "It is not that we have a short time to live, but that we waste a lot of it.", by: "Seneca" },
  { text: "Luck is what happens when preparation meets opportunity.", by: "Seneca" },
  { text: "Begin at once to live, and count each separate day as a separate life.", by: "Seneca" },
  { text: "We suffer more often in imagination than in reality.", by: "Seneca" },
  { text: "No man is free who is not master of himself.", by: "Epictetus" },
  { text: "First say to yourself what you would be; and then do what you have to do.", by: "Epictetus" },
  { text: "It's not what happens to you, but how you react to it that matters.", by: "Epictetus" },
  { text: "The journey of a thousand miles begins with a single step.", by: "Lao Tzu" },
  { text: "When I let go of what I am, I become what I might be.", by: "Lao Tzu" },
  { text: "Nature does not hurry, yet everything is accomplished.", by: "Lao Tzu" },
  { text: "Knowing others is intelligence; knowing yourself is true wisdom.", by: "Lao Tzu" },
  { text: "It does not matter how slowly you go as long as you do not stop.", by: "Confucius" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", by: "Confucius" },
  { text: "The man who moves a mountain begins by carrying away small stones.", by: "Confucius" },
  { text: "Wherever you go, go with all your heart.", by: "Confucius" },
  { text: "The wound is the place where the light enters you.", by: "Rumi" },
  { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", by: "Rumi" },
  { text: "What you seek is seeking you.", by: "Rumi" },
  { text: "Raise your words, not your voice. It is rain that grows flowers, not thunder.", by: "Rumi" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", by: "Ralph Waldo Emerson" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", by: "Ralph Waldo Emerson" },
  { text: "The only person you are destined to become is the person you decide to be.", by: "Ralph Waldo Emerson" },
  { text: "Write it on your heart that every day is the best day in the year.", by: "Ralph Waldo Emerson" },
  { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", by: "Henry David Thoreau" },
  { text: "It's not what you look at that matters, it's what you see.", by: "Henry David Thoreau" },
  { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", by: "Henry David Thoreau" },
  { text: "Keep your face always toward the sunshine, and shadows will fall behind you.", by: "Walt Whitman" },
  { text: "Be curious, not judgmental.", by: "Walt Whitman" },
  { text: "We are all in the gutter, but some of us are looking at the stars.", by: "Oscar Wilde" },
  { text: "Be yourself; everyone else is already taken.", by: "Oscar Wilde" },
  { text: "Hope is the thing with feathers that perches in the soul.", by: "Emily Dickinson" },
  { text: "Dwell in possibility.", by: "Emily Dickinson" },
  { text: "Energy and persistence conquer all things.", by: "Benjamin Franklin" },
  { text: "Well done is better than well said.", by: "Benjamin Franklin" },
  { text: "By failing to prepare, you are preparing to fail.", by: "Benjamin Franklin" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", by: "Will Durant, after Aristotle" },
  { text: "It is during our darkest moments that we must focus to see the light.", by: "Aristotle" },
  { text: "Pleasure in the job puts perfection in the work.", by: "Aristotle" },
  { text: "The secret of change is to focus all of your energy not on fighting the old, but on building the new.", by: "attributed to Socrates" },
  { text: "An unexamined life is not worth living.", by: "Socrates" },
  { text: "The first and greatest victory is to conquer yourself.", by: "Plato" },
  { text: "Never discourage anyone who continually makes progress, no matter how slow.", by: "Plato" },
  { text: "What we think, we become.", by: "attributed to the Buddha" },
  { text: "No matter how hard the past, you can always begin again.", by: "Buddhist saying" },
  { text: "Drop by drop is the water pot filled.", by: "the Dhammapada" },
  { text: "Peace comes from within. Do not seek it without.", by: "Buddhist saying" },
  { text: "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things.", by: "Leonardo da Vinci" },
  { text: "Learning never exhausts the mind.", by: "Leonardo da Vinci" },
  { text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", by: "Johann Wolfgang von Goethe" },
  { text: "Whatever you can do or dream you can, begin it. Boldness has genius, power and magic in it.", by: "attributed to Goethe" },
  { text: "He who has a why to live can bear almost any how.", by: "Friedrich Nietzsche" },
  { text: "You must have chaos within you to give birth to a dancing star.", by: "Friedrich Nietzsche" },
  { text: "Everyone thinks of changing the world, but no one thinks of changing himself.", by: "Leo Tolstoy" },
  { text: "The two most powerful warriors are patience and time.", by: "Leo Tolstoy" },
  { text: "If you hear a voice within you say 'you cannot paint,' then by all means paint, and that voice will be silenced.", by: "Vincent van Gogh" },
  { text: "Great things are done by a series of small things brought together.", by: "Vincent van Gogh" },
  { text: "Normality is a paved road: it's comfortable to walk, but no flowers grow on it.", by: "Vincent van Gogh" },
  { text: "In the middle of difficulty lies opportunity.", by: "attributed to Albert Einstein" },
  { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", by: "Albert Einstein" },
  { text: "Fall seven times, stand up eight.", by: "Japanese proverb" },
  { text: "The best time to plant a tree was twenty years ago. The second best time is now.", by: "proverb" },
  { text: "A smooth sea never made a skilled sailor.", by: "proverb" },
  { text: "Little by little, one travels far.", by: "Spanish proverb" },
  { text: "However long the night, the dawn will break.", by: "African proverb" },
  { text: "If you want to go fast, go alone. If you want to go far, go together.", by: "African proverb" },
  { text: "When the winds of change blow, some people build walls and others build windmills.", by: "Chinese proverb" },
  { text: "Be not afraid of growing slowly, be afraid only of standing still.", by: "Chinese proverb" },
  { text: "The best fighter is never angry.", by: "Lao Tzu" },
  { text: "A gem cannot be polished without friction, nor a person perfected without trials.", by: "Chinese proverb" },
  { text: "Vision without action is a daydream. Action without vision is a nightmare.", by: "Japanese proverb" },
  { text: "He who conquers himself is the mightiest warrior.", by: "Confucius" },
  { text: "Do the difficult things while they are easy and do the great things while they are small.", by: "Lao Tzu" },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", by: "Oscar Wilde" },
  { text: "Nothing will work unless you do.", by: "Maya Angelou" },
  { text: "You may not control all the events that happen to you, but you can decide not to be reduced by them.", by: "Maya Angelou" },
  { text: "Courage is the most important of all the virtues, because without courage you can't practice any other virtue consistently.", by: "Maya Angelou" },
  { text: "It always seems impossible until it's done.", by: "Nelson Mandela" },
  { text: "Do not judge me by my successes, judge me by how many times I fell down and got back up again.", by: "Nelson Mandela" },
  { text: "You must do the things you think you cannot do.", by: "Eleanor Roosevelt" },
  { text: "No one can make you feel inferior without your consent.", by: "Eleanor Roosevelt" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", by: "Eleanor Roosevelt" },
  { text: "Happiness is not something ready made. It comes from your own actions.", by: "the 14th Dalai Lama" },
  { text: "Out of the mountain of despair, a stone of hope.", by: "Martin Luther King Jr." },
  { text: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but by all means keep moving.", by: "Martin Luther King Jr." },
  { text: "What you do today can improve all your tomorrows.", by: "Ralph Marston" },
  { text: "Small daily improvements are the key to staggering long-term results.", by: "unknown" },
  { text: "You don't have to see the whole staircase, just take the first step.", by: "Martin Luther King Jr." },
  { text: "Discipline is choosing between what you want now and what you want most.", by: "unknown" },
  { text: "Your future self is watching you right now through your memories.", by: "unknown" },
  { text: "A river cuts through rock not because of its power, but because of its persistence.", by: "unknown" },
  { text: "Don't count the days; make the days count.", by: "Muhammad Ali" },
  { text: "The wheel turns because you turn it. One honest page at a time.", by: "Twølve" },
  { text: "You cannot pour from an empty cup. Tend to every area, a little, often.", by: "unknown" },
  { text: "Where attention goes, energy flows.", by: "unknown" },
  { text: "Comparison is the thief of joy.", by: "attributed to Theodore Roosevelt" },
  { text: "Start where you are. Use what you have. Do what you can.", by: "Arthur Ashe" }
];
